# Aula de Estatistica 

Listas

- Mutáveis.
- Ordenadas.
- Heterogêneas.
- Indexada por posição.
- Delimitada por Colchetes.

In [2]:
lista = ['casa', 1.0,3]

In [3]:
type(lista)

list

In [4]:
lista[0]

'casa'

In [5]:
lista[1]

1.0

In [8]:
lista[2]

3

In [10]:
lista[-1]

3

Um problema serio com listas!

In [14]:
a = [1,2,3]

In [17]:
a

[1, 2, 3]

In [18]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [16]:
b = []
for i in a:
    b.append(i*3)
b

[3, 6, 9]

Dicionarios

- Não mutaveis.
- Não ordenados.
- Heterogeneos .
- Indexada por chaves.
- delimitadas por chaves.

In [21]:
dicionario = {"nome":"rennyson","idade":18,"cidade":"nazarezinho"}

In [22]:
type(dicionario)

dict

In [23]:
dicionario["idade"]

18

In [25]:
dicionario["nome"]

'zé'

ndarray - Numpy

- A biblioteca numpy cria uma nova estrutura de dados, tem uma grande capacidade de vetorização que possibilita que qualquer operação feita com estrutura ja feita elemento a elemento sem a necessidade de um laço para acessar esses elementos, tornando, assim, a operação mais eficiente.

In [32]:
import numpy as np

In [30]:
np.array([-2,4.4,7,9])

array([-2. ,  4.4,  7. ,  9. ])

Existem varias formas de criar arrays, pode ser através do método np.array{}:

1. usando uma lista:

In [35]:
arr = np.array([-2,4,7,9])
arr

array([-2,  4,  7,  9])

**OBS: A lista deve ser homonogenea.**
ORDEM: String > complex > float > int 

ex: se a lista tiver só inteiros o resultado dará só inteiros,
se a lista tiver um float e o resto inteiro ele converte todos para float

2. usando o método arange: **np.arange(inicio, fim , passo)**

In [42]:
arr = np.arange(1,32,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

3. usando o método linspace: **np.linspace (inicio, fim, quantidade)**

In [45]:
arr = np.linspace(1, 100, 10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

4. outros métodos

In [49]:
arr1 = np.empty((6,4)) ##array vazia com o método empty() normalmente a saída lida
arr1

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306],
       [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511290e-306],
       [1.78019082e-306, 8.45559303e-307, 8.06613040e-308,
        6.89810244e-307],
       [1.22387550e-307, 2.22522596e-306, 8.34423917e-308,
        9.79107193e-307]])

In [50]:
arr2 = np.eye(4) #eye cria uma array de duas dimensões com 1 na diagonal e 1 linha
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Criar as arrays de A E B para fazer operações com elas

In [59]:
A = np.arange(10)
B = np.arange(10,38,3)
c = np.array([2,3,4,5,6,7,8,9, np.nan , np.nan])
print('\nA:' , A , '\nB:', B, '\nc:',c)


A: [0 1 2 3 4 5 6 7 8 9] 
B: [10 13 16 19 22 25 28 31 34 37] 
c: [ 2.  3.  4.  5.  6.  7.  8.  9. nan nan]


In [60]:
A+c

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., nan, nan])

In [56]:
somar = A + B
subtrair = A - B
multiplicar = A * B
dividir = A / B

print('\n\nsomar: ', somar)
print('\nsubtrair: ',subtrair)
print('\ndividir: ', dividir)
print('\nmultiplicar:', multiplicar)




somar:  [10 14 18 22 26 30 34 38 42 46]

subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]

dividir:  [0.         0.07692308 0.125      0.15789474 0.18181818 0.2
 0.21428571 0.22580645 0.23529412 0.24324324]

multiplicar: [  0  13  32  57  88 125 168 217 272 333]
